#!/bin/bash

set -o errexit

rm -rf /a/local/build
mkdir --parents /a/local/build/0

cp /a/index.html /a/local/build/0/index.html
cp --recursive /a/source/static /a/local/build/0/static

function build_page() {
	pandoc --standalone /a/source/page/$1.md --output /a/local/build/0/$1.html --template /a/source/template.html
}

function call() {
	while read x; do
		$1 $x
	done
}

find /a/source/page -type f -name "*.md" | sed "s|/a/source/page/||" | sed "s|.md||" | call build_page

python /a/script/publish/rewrite.py
