#!/bin/bash

set -o errexit

rm -rf /a/local/build
mkdir --parents /a/local/build-production/0

cp --recursive /a/source/static /a/local/build-production/0/static

function build_page() {
	pandoc --standalone /a/source/page/$1.md --output /a/local/build-production/0/$1.html --template /a/source/template.html
}

function each() {
	while read x; do
		$1 $x
	done
}

find /a/source/page -type f -name "*.md" | sed "s|/a/source/page/||" | sed "s|.md||" | each build_page

python /a/script/publish/rewrite.py
