#!/bin/bash

set -o errexit

rm -rf /a/local/build
mkdir --parents /a/local/build

# function build_page() {
# 	mkdir --parents /a/local/build/$1/..
# 	python -m mistune --file /a/source/page/$1.md --output /a/local/build/$1.html
# }
#
# function each() {
# 	while read x; do
# 		$1 $x
# 	done
# }
#
# cp --recursive /a/source/static /a/local/build/static
# find /a/source/page -type f -name "*.md" | sed "s|/a/source/page/||" | sed "s|.md||" | each build_page

cd /a/source
source /a/script/activate
python -m app
export FLASK_FREEZER_DESTINATION=/a/local/build/0
python freeze.py
python rewrite.py
# mv /a/local/build/0/index /a/local/build/0/index.html
