#!/bin/bash

set -o errexit

rm -rf /a/local/build
mkdir --parents /a/local/build

cp --recursive /a/source/static /a/local/build/static

export PYTHONIOENCODING=utf-8

function build_page() {
	# pandoc --standalone /a/source/page/$1.md --output /a/local/build/$1.html --template /a/source/template.html
	mkdir --parents /a/local/build/$1/..
	python -m mistune --file /a/source/page/$1.md --output /a/local/build/$1.html
}

function each() {
	while read x; do
		$1 $x
	done
}

find /a/source/page -type f -name "*.md" | sed "s|/a/source/page/||" | sed "s|.md||" | each build_page
