#!/bin/bash

set -o errexit

# cd /a/source
# echo "http://localhost:8000"
# python -m http.server
# python -m httpmdhtml.server

mkdir --parents /a/local/run
cd /a/local/run
echo "http://localhost:5000"
source /a/script/activate
flask --app /a/source/app run --debug
