#!/bin/bash

set -o errexit

# cd /a/local/build
# echo "http://localhost:8000"
# python -m http.server
# python -m httpmdhtml.server

# cd /a/local/build
# echo "http://localhost:5000"
# source /a/script/activate
# flask --app /a/source/app run --debug

pelican --listen /a/local/source --output /a/local/build --theme-path /a/source/theme
